### ISSUE TITLE
requested feature

### ISSUE THREAD

**Issue by Sandvoxel** [FabioZumbi12/Sponge-PixelAutoMessage#1]
This is a requested feature but could a command be added to remove the messages on a player by player basis.

**Comment by FabioZumbi12** [comment]
Just set a permission and negate the permision to that player/group: `c-permission=""`

**Comment by CrazyGrape** [comment]
The idea is that we'd like players of a certain group to be able to opt out of the messages at their own discretion.

**Comment by FabioZumbi12** [comment]
I dont want to add a file manager and save what player should receive/ignore a message. The best way is you use a command-alias (in other plugin) and allow the player to use this command to add a self negative permission for one message (or all if you set the same permission for all messages)

**Comment by CrazyGrape** [comment]
Alright, thank you for your advice.
