### ISSUE TITLE
Messages dont work anymore

### ISSUE THREAD

**Issue by YumaYamamoto** [FabioZumbi12/Sponge-PixelAutoMessage#2]
After I edited the messages the broadcast dont worry anymore why?

configs {
    interval=60
    prefix="&4[Information]& "
    random=false
}
# Set you messages here! Follow the example and add numbers as index for more messages. 
# All fields (except permission) accept the player placeholder {player}.
# 
# Note: Use the fields 'click-cmd', 'click-url' and 'suggest-cmd' one at time.
messages {
    "0" {
        # Any colored message to send to server
        a-message="&a{player}, du kannst eine Auktion hier auf dem Server mit /auc start [Startpreis] eröffnen"
        # Players online needed to show this message. Set 0 always show.
        b-players-online=0
        # Set permissions needed to player receive this message. Leave blank to disable.
        c-permission=""
        # Colored hover message.
        d-on-hover="&7Dafür halte das Item was du verkaufen möchtest doch bitte in der Hand."
        # Print a command on player chat.
        e-suggest-cmd="/auc"
    }
    "1" {
        # Any colored message to send to server
        a-message="&a{player}, es gibt hier auch Berufe, diese kannst du dir mit /job set [name] auswählen."
        # Players online needed to show this message. Set 0 always show.
        b-players-online=0
        # Set permissions needed to player receive this message. Leave blank to disable.
        c-permission=""
        # Colored hover message.
        d-on-hover="&7Folgende Berufe gibt es: bergarbeiter, holzfäller, farmer, fischer, krieger und arbeitslos"
    }
    "2" {
        # Any colored message to send to server
        a-message="&a{player}, ein Tutorial wie du dir dein Grundstück sichern kannst, gibt es im Discord!"
        # Players online needed to show this message. Set 0 always show.
        b-players-online=0
        # Set permissions needed to player receive this message. Leave blank to disable.
        c-permission=""
        # Colored hover message.
        d-on-hover="&7Also komm doch auf unseren Discord, wenn du nicht schon drauf bist!"
    }
    "3" {
        a-message="&a{player}, wenn du nicht auf unserem Discord bist, dann würden wir dir dies empfehlen! "
        b-players-online=0
        c-permission=""
        d-on-hover="&7Auf dem Discord findest du auch noch vieles weitere!"
        g-click-url="https://discord.gg/5MM5UQx"
    }
    "4" {
        a-message="&a{player}, wenn du uns unterstützen möchtest dann spende doch, du erhältst dadurch auch viele und coole VIP Zusätze."
        b-players-online=0
        c-permission=""
        d-on-hover="&7Der VIP Rank kostet derzeit nur 5€! Also greif zu!"
        g-click-url="https://ultimatemodpack.craftingstore.net/"
    }
}

**Comment by FabioZumbi12** [comment]
Probally a mistake on config. On next time paste on gist.github.

**Comment by YumaYamamoto** [comment]
What the fuck? So you dont help me and just close it... good author really good job haha :D

**Comment by FabioZumbi12** [comment]
> After I edited the messages the broadcast dont worry anymore

I dont need to do anything to help you, you already answered your question! Just redo your changes and try again. Or you need some people to tell you to do this before you try?

**Comment by YumaYamamoto** [comment]
Yeah you are really an asshole. As I didnt redo the changes ofc it works then. But I even posted my config and you not even check it. Dont do plugins if you dont care about helping anyone asshole.

**Comment by Sandvoxel** [comment]
lmao
